# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Jonathan Lin
tagline:          'Physician Engineer'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jonathan Lin'
  url:            https://jonlin.zone/

paginate:         5

# Custom vars

github:
  repo:           https://github.com/poole/hyde
plugins:	  [jekyll-paginate, jekyll-gist]