# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Jonathan Lin'
tagline:          'Physician Engineer'
description:      'Engineer and Physician in Training.'
url:              http://jonlin.zone
baseurl:          /

author:
  name:           'Jonathan Lin'
  url:            https://jonlin.zone/

paginate:         5

# Custom vars

github:
  repo:           https://github.com/poole/hyde
plugins:	  [jekyll-paginate, jekyll-gist]